name: Build and Deploy Raylib Wasm Game to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 4.0.11

    - name: Build web version
      run: |
        make web
        mkdir -p build_web
        mv index.* build_web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build_web
        publish_branch: gh-pages

